function get() {
  return JSON.parse(
    localStorage.getItem("blog_posts") || "[]",
  );
}
function add() {
  let val = document.getElementById("inp").value.trim();
  if (!val) return;
  let data = get();
  data.push(val);
  localStorage.setItem("blog_posts", JSON.stringify(data));
  document.getElementById("inp").value = "";
  ren();
}
function edit(i) {
  let data = get();
  let newVal = prompt("Edit Post Title:", data[i]);
  if (newVal && newVal.trim()) {
    data[i] = newVal.trim();
    localStorage.setItem(
      "blog_posts",
      JSON.stringify(data),
    );
    ren();
  }
}
function del(i) {
  let data = get();
  data.splice(i, 1);
  localStorage.setItem("blog_posts", JSON.stringify(data));
  ren();
}
function ren() {
  document.getElementById("list").innerHTML = get()
    .map(
      (item, index) => `
    <li style="display:flex; justify-content:space-between; margin-bottom:10px; padding:10px; background:rgba(255,255,255,0.1); border-radius:4px;">
      <span>${item}</span>
      <div>
        <button onclick="edit(${index})" style="background:#fbbf24; border:none; border-radius:3px; padding:3px 8px; cursor:pointer; font-weight:bold; color:#000;">Edit</button>
        <button onclick="del(${index})" style="background:#f72585; border:none; border-radius:3px; padding:3px 8px; cursor:pointer; font-weight:bold; color:#fff;">Del</button>
      </div>
    </li>
  `,
    )
    .join("");

  // Optionally dynamically update the actual "Recent Posts" section for coolness
  const realPostContainer = document.querySelector("main");
  let defaultHTML = `<article><h2>Post Title</h2><p>This is the main blog post content...</p></article>`;
  if (get().length === 0) {
    realPostContainer.innerHTML = defaultHTML;
    return;
  }
  realPostContainer.innerHTML = get()
    .map(
      (item) =>
        `<article><h2>${item}</h2><p>Autogenerated content for ${item} because you added it via CRUD. Wow such dynamic!</p></article>`,
    )
    .join("");
}
ren();
